
networks:
  roboshop:
    driver: bridge
services:
 web:
  image: web:v1
  conatainer_name: web
  depends_on:
  - catalogue
 mongodb:
  image: mongodb:v1
  container_name: mongodb
 catalogue:
  image: catalogue:v1
  conatainer_name: catalogue
  depends_on:
  - mongodb
 redis:
  image: redis
 user:
  image: user:v1
  conatainer_name: user
  depends_on: 
  - mongodb
  - redis
